spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    database: student_manager
    url: jdbc:mysql://${datasource.host}:3306/${datasource.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: student_admin
    password: students
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB


mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml

